### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by xrotwang** [lexibank/seabor#3]
- [x] release lingrex
- [x] fix deps, run workflow with released versions of all deps
- [x] wire up with zenodo
- [x] re-run / re-create all figures for paper

**Comment by LinguList** [comment]
- [x] add swadesh.py (I am working on that now)

**Comment by LinguList** [comment]
The permutation test for concepts turned out to be not "significant" for leipzig jakarta, when runnint 1000 trials. To be sure to obtain similar results, I'll now increase to 10000 trials and then push the updated code.

**Comment by LinguList** [comment]
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5028747.svg)](https://doi.org/10.5281/zenodo.5028747)

**Comment by LinguList** [comment]
LingRex is now released, and I also completed the workflow.

**Comment by LinguList** [comment]
- [ ] check with paper to include Zenodo links and the like, update references (check that lingrex is version 1.1.0)

**Comment by LinguList** [comment]
By now, the metadata.json does not link to the journal where we will submit to, but since this is post-pub-review, I think we can release v0.1.0 today and then we can release v1.0.0, maybe with a proper concept list submitted to concepticon with some numbers on stability or the like, later, when updating the study.

**Comment by xrotwang** [comment]
We could link from workflow.md to the plots in `plots/`. But they are big, and don't render well within github, so maybe we could just mention them - or create JPG version?

**Comment by LinguList** [comment]
JPG may be best for this purpose. Since the plots have the heavy boundaries and need to be cropped, which is easier to do post-hoc, I prefer PDF versions for editing and making final versions for publications, but for the workflow online, JPG or maybe even SVG may indeed be useful.

**Comment by xrotwang** [comment]
JPG images inlined: https://github.com/lexibank/seabor/blob/main/workflow.md

**Comment by xrotwang** [comment]
Should we add a citation recommendation for lingrex in a NOTES.md ?

**Comment by LinguList** [comment]
Yes, that may be useful.

**Comment by LinguList** [comment]
My practice now also for lingpy and other bigger software packages is like the one I use on .zenodo.json: https://zenodo.org/record/5028747

> List, Johann-Mattis and Robert Forkel (2021): LingRex. Linguistic reconstruction with LingPy. Version 1.1.0. URL: https://github.com/lingpy/lingrex, DOI: https://doi.org/10.5281/zenodo.1544943. Leipzig: Max Planck Institute for Evolutionary Anthropology.

**Comment by LinguList** [comment]
The DOI is the one DOI that quotes them all.

**Comment by xrotwang** [comment]
Why the mpi as publisher and not zenodo?

Johann-Mattis List ***@***.***> schrieb am Sa., 26. Juni
2021, 10:56:

**Comment by LinguList** [comment]
I have been quoting lingpy like this for years now, based on a recommendation by Martin Haspelmath back in 2014, to use the university as publisher and the location of the university as address. This is easiest for people to understand, as it looks like a book. Zenodo is still unclear, as it does not fit the typical "book" publication scheme. I'd also say: Zenodo is not necessarily the publisher, because you could also say the publisher is pypi, etc., etc. So I find the "@book"-style advantageous.

**Comment by xrotwang** [comment]
The most important part of the reference is the DOI,  I'd say. And if you
use the DOI to lookup the metadata, you'll end up with a different citation
than the one you recommend. So I'd say the publisher is whoever controls
the DOI.

Johann-Mattis List ***@***.***> schrieb am Sa., 26. Juni
2021, 13:57:

**Comment by LinguList** [comment]
The doi as i suggest we put this on the list of things to discuss next week. I have some in my opinion important arguments, but they would take too lo g to write them up here. Will be faster in person.

**Comment by LinguList** [comment]
I realize one should not write from mobile phone in github. I still suggest to quickly talk this through on Monday. I saw that Zenodo now suggests itself as publisher in the bibtex they create, which is a progress to their earlier citation suggestions, so this means it is time to change and make zenodo the publisher, but we'll still need to discuss details and ideally pin this down, as it will apply to quite a few projects where we should try to go for consistent "how to cite" practices, where the practices I have been using so far diverge.
